# Name your project! Project names should contain only lowercase characters
# and underscores.
name: "pricing_difference"
version: "1.0.0"

# This setting configures which profile dbt uses.
profile: "pricing_difference"

# Directories where dbt looks for project files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  pricing_difference:

    # Staging models
    staging:
      +materialized: view
      +schema: staging

    # Mart models
    marts:
      +materialized: table
      +schema: marts