version: 2

sources:
  - name: pricing_difference
    database: PRICING_DIFF
    schema: raw
    config:
      freshness:
        warn_after:
          count: 24
          period: hour
        error_after:
          count: 48
          period: hour

    tables:
      - name: competitor_pricing
        columns:
          - name: comparison_id
            data_tests:
              - unique
              - not_null
